version: '2'
services:
  ship_service:
    container_name: ship_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge