# =============MySQL config==================
spring:
  application: ship-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://103.159.51.154:3306/ship_service
    username: root
    password: Cuonglinh1711@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mandatory-file-encoding: UTF-8
  messages:
    basename: classspath:message
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cuongnv
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  redis:
    host: localhost
    port: 6379
    password: 12345678
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  api-docs:
    path:  /javainuse-openapi
# ============LOG4J / HIBERNATE=================
logging:
  level:
    org.springframework.web: DEBUG
    vn.clmart.manager_service: INFO
    org.hibernate.type: error
server:
  port: 8087
  error:
    include-message: always
  servlet:
    session:
      timeout: 1000m
      cookie:
        http-only: true
      tracking-modes: cookie
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      mvc:
        hiddenmethod:
          filter:
            enabled: true
  session:
    tracking-modes: cookie
# ============SECURITY=================
#rabbitmp:
#  queue_name: queue_name
#  exchange_name: exchange_name
#  routing_key: rabbitmq.*


